# Generated by Django 5.0.6 on 2024-06-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='care',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='zipcode',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
